name: fpr
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0" # Ensure compatibility with the Flutter version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.0  # For formatting dates
  shared_preferences: ^2.0.15  # For storing simple data
  get: ^4.6.5  # For state management
  http: ^1.1.0  # For making HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/  # Add your custom images directory if needed
    - assets/fonts/   # Add your custom fonts directory if needed
